name: Pancho Burgos-Goizueta
favicon: null
layout_spectrum: 0.08782
typography_spectrum: 0.60701
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0505'
    - '#ffffff'
    - '#2e2118'
    - '#625c5d'
    - '#658079'
  brandStrength: 0.5
  lightness: 0.5895045700017363
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
